version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        env_file:
        - .env
        ports:
        - ${DB_PORT}:${DB_PORT}
        environment:
        - PUID=1000
        - PGID=1000
        - mongodb://${DB_HOST}:${DB_PORT}/EWALLET
        
        volumes:
            - "./mongodb/database:/data/db"
        restart: always
volumes:
    dbdata: