version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        env_file:
        - .env
        ports:
        - "27017:27017"
        environment:
        - PUID=1000
        - PGID=1000
        - mongodb://localhost:27017/EWALLET
        
        volumes:
            - "./mongodb/database:/data/db"
volumes:
    dbdata: